---
name: Lint JSON Resume

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - 'feature/*'
      - 'fix/*'
      - 'release/*'
  pull_request:
    branches:
      - develop
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint with JSON Lint
        env:
          REPORT_ONLY: true
          SHOW_ERRORS: true
          SHOW_SKIPPED: true
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/json-lint/master/pipeline.sh)
...